# Generated by Django 3.0.2 on 2020-01-09 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200109_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='restaurant_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
