# Generated by Django 3.0.2 on 2020-01-09 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_menu_restaurant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='budget',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
    ]
