# Generated by Django 3.0.2 on 2020-01-11 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200111_0702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='non_veg_main_course',
            new_name='non_veg_main_course_count',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='veg_main_course',
            new_name='veg_main_course_count',
        ),
    ]
