# Generated by Django 3.0.2 on 2020-01-11 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200111_0703'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='price',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
