# Generated by Django 3.0.2 on 2020-01-12 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_package_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='lat',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='lng',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='budget',
            field=models.DecimalField(decimal_places=1, max_digits=10, null=True),
        ),
    ]
