# Generated by Django 3.0.2 on 2020-01-12 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200112_0546'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='firebase_id',
            field=models.CharField(max_length=140, null=True),
        ),
    ]
