# Generated by Django 3.0.2 on 2020-01-12 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_restaurant_firebase_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='tags',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
