# Generated by Django 3.0.2 on 2020-01-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_restaurant_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='featured_thumbnail',
            field=models.ImageField(null=True, upload_to='images/featured_thumbnail'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='image_1',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='image_2',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='image_3',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
